#############################################################################
# Makefile for building: FirstProject
# Generated by qmake (3.1) (Qt 6.2.1)
# Project:  FirstProject.pro
# Template: app
# Command: D:\WorkSoftware\Qt\6.2.1\msvc2019_64\bin\qmake.exe -o Makefile FirstProject.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = D:\WorkSoftware\Qt\6.2.1\msvc2019_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\WorkSoftware\Qt\6.2.1\msvc2019_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\WorkSoftware\Qt\6.2.1\msvc2019_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = FirstProject_resource.res
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: FirstProject.pro ..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\win32-msvc\qmake.conf ..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\spec_pre.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\common\windows-desktop.conf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\common\windows-vulkan.conf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\common\msvc-desktop.conf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\qconfig.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_ext_freetype.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_ext_libpng.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_activeqt.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_activeqt_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_bodymovin_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_charts.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_chartsqml.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_chartsqml_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_core.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_datavisualization.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_datavisualization_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_designer.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_entrypoint_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_help.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labsanimation.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labsanimation_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labssettings.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labssettings_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_linguist.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_linguist_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_multimediaquick_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_network.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_networkauth.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_networkauth_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_nfc.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_positioning.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_positioningquick.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_positioningquick_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmlcore.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmlcore_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmldom_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_repparser.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_repparser_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_scxml.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_scxml_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_serialbus.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_serialport.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_statemachine.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_statemachine_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_tools_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webenginecore.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webenginequick.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webenginequick_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_websockets.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webview.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webviewquick.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webviewquick_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\qt_functions.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\qt_config.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\win32-msvc\qmake.conf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\exclusive_builds.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\common\msvc-version.conf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\toolchain.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\default_pre.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\win32\default_pre.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\resolve_config.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\exclusive_builds_post.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\default_post.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\qtquickcompiler.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\entrypoint.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\precompile_header.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\warn_on.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\qt.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\resources_functions.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\resources.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\moc.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\win32\opengl.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\uic.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\qmake_use.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\file_copies.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\win32\windows.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\testcase_targets.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\exceptions.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\yacc.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\lex.prf \
		FirstProject.pro \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\lib\Qt6Widgets.prl \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\lib\Qt6Gui.prl \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\lib\Qt6Core.prl \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\lib\Qt6EntryPoint.prl \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\build_pass.prf \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\lib\Qt6Widgetsd.prl \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\lib\Qt6Guid.prl \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\lib\Qt6Cored.prl \
		..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\lib\Qt6EntryPointd.prl
	$(QMAKE) -o Makefile FirstProject.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\spec_pre.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\common\windows-desktop.conf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\common\windows-vulkan.conf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\common\msvc-desktop.conf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\qconfig.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_ext_freetype.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_ext_libpng.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_activeqt.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_activeqt_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_bodymovin_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_charts.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_chartsqml.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_chartsqml_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_core.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_datavisualization.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_datavisualization_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_designer.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_entrypoint_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_gui.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_help.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labsanimation.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labsanimation_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labssettings.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labssettings_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_linguist.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_linguist_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_multimediaquick_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_network.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_networkauth.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_networkauth_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_nfc.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_positioning.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_positioningquick.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_positioningquick_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qml.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmlcore.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmlcore_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmldom_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quick.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_repparser.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_repparser_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_scxml.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_scxml_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_serialbus.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_serialbus_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_sql.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_statemachine.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_statemachine_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_svg.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_tools_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webchannel.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webenginecore.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webenginequick.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webenginequick_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_websockets.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webview.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webview_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webviewquick.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_webviewquick_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_xml.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\qt_functions.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\qt_config.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\win32-msvc\qmake.conf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\spec_post.prf:
.qmake.stash:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\exclusive_builds.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\common\msvc-version.conf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\toolchain.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\default_pre.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\win32\default_pre.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\resolve_config.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\exclusive_builds_post.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\default_post.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\qtquickcompiler.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\entrypoint.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\precompile_header.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\warn_on.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\qt.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\resources_functions.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\resources.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\moc.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\win32\opengl.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\uic.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\qmake_use.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\file_copies.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\win32\windows.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\testcase_targets.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\exceptions.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\yacc.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\lex.prf:
FirstProject.pro:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\lib\Qt6Widgets.prl:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\lib\Qt6Gui.prl:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\lib\Qt6Core.prl:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\lib\Qt6EntryPoint.prl:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\mkspecs\features\build_pass.prf:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\lib\Qt6Widgetsd.prl:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\lib\Qt6Guid.prl:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\lib\Qt6Cored.prl:
..\..\..\WorkSoftware\Qt\6.2.1\msvc2019_64\lib\Qt6EntryPointd.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile FirstProject.pro -spec win32-msvc "CONFIG+=qtquickcompiler"

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
